In [1]:
import numpy as np
import matplotlib.pyplot as plt
import string

import os
from HMM import HMM
from collections import Counter
from itertools import chain
from tqdm import tqdm
import pickle

In [2]:
transition_probs = np.asarray([[0.8, 0.2, 0.0], [0.0, 0.8, 0.2], [0.0, 0.0, 0.8]], dtype=np.float64)
non_zero_arcs = np.where(transition_probs > 0)

In [4]:
x = [0,1,2,3,4,5,6,7]
x[0:2+1] + x[5:-1]

[0, 1, 2, 5, 6]

In [2]:
np.asarray([[1.0]], dtype=np.float64).shape

(1, 1)

In [4]:
np.asarray([[[1.0] * 286]], dtype=np.float64).shape

(1, 1, 286)

In [5]:
data_dir = "./data"

def read_file_line_by_line(file_name, func=lambda x: x, skip_header=True):
    print("reading file: %s" % file_name)
    res = list()
    with open(file_name, "r") as fin:
        if skip_header:
            fin.readline()  # skip the header
        for line in fin:
            if len(line.strip()) == 0:
                continue
            fields = func(line.strip())
            res.append(fields)
    print("%d lines, done" % len(res))
    return res

In [7]:
scr = "ana"

In [10]:
transition_matrix = np.zeros((5*2 + len(scr)*3, 5*2 + len(scr)*3))

In [12]:
transition_matrix[-5:,-5:]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
import numpy as np
np.array([[[1, 0.5, 1], [0, 0, 1.0/3], [0, 0, 0]], [[0, 0.5, 0], [1, 1, 2.0/3], [1, 1, 1]]]).shape

(2, 3, 3)

In [5]:
from collections import defaultdict
defaultdict(lambda: defaultdict(lambda: 0))

defaultdict(<function __main__.<lambda>()>, {})

In [7]:
np.ones(6)[:-1]

array([1., 1., 1., 1., 1.])

In [3]:
import numpy as np
np.asarray([1] + [0] * (5- 1), dtype=np.float64)

array([1., 0., 0., 0., 0.])